// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/info": {
            "get": {
                "description": "provides server info",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "Info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.Info"
                        }
                    }
                }
            }
        },
        "/metrics": {
            "get": {
                "description": "provides RabbitMQ metrics",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "example"
                ],
                "summary": "metrics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.QueueInfo"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.Info": {
            "type": "object",
            "properties": {
                "compile_date": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "log_level": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.QueueInfo": {
            "type": "object",
            "properties": {
                "messages": {
                    "type": "integer"
                },
                "messages_ready": {
                    "type": "integer"
                },
                "messages_unacknowledged": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8090",
	BasePath:         "/api/v1/",
	Schemes:          []string{"http"},
	Title:            "Metrics API",
	Description:      "API for Metrics",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
